SELECT DISTINCT
 p.AN_BASE,
 p.SG_ENTIDADE_ENSINO,
 p.NM_ENTIDADE_ENSINO,
 p.DS_DEPENDENCIA_ADMINISTRATIVA,
 p.CD_PROGRAMA_IES,
 p.NM_PROGRAMA_IES,
 p.NM_MODALIDADE_PROGRAMA,
 p.NM_GRAU_PROGRAMA,
 p.CD_CONCEITO_PROGRAMA,
 p.DS_SITUACAO_PROGRAMA,
 p.NM_GRANDE_AREA_CONHECIMENTO,
 p.NM_AREA_BASICA,
 p.CD_AREA_AVALIACAO,
 p.NM_AREA_AVALIACAO,
 p.NM_REGIAO,
 p.SG_UF_PROGRAMA,
 p.NM_ESTADO,
 p.NM_MUNICIPIO_PROGRAMA_IES,
 ap.ID_LINHA_PESQUISA,
 ap.NM_LINHA_PESQUISA,
 ap.ID_PROJETO,
 ap.NM_PROJETO,
 f.NM_NATUREZA_FINANCIAMENTO,
 f.NM_FINANCIADOR,
 f.NM_PROGRAMA_FOMENTO,
 ap.ID_ADD_PRODUCAO_INTELECTUAL,
 ap.ID_PRODUCAO_INTELECTUAL,
 ap.NM_PRODUCAO,
 ap.NM_TIPO_PRODUCAO,
 ap.NM_SUBTIPO_PRODUCAO,
 ap.CD_IDENTIFICADOR_VEICULO,
 ap.DS_TITULO_PADRONIZADO,
 au.ID_PESSOA_DISCENTE,
 au.ID_PESSOA_DOCENTE,
 au.ID_PESSOA_EGRESSO,
 au.ID_PESSOA_PART_EXTERNO,
 au.ID_PESSOA_POS_DOC,
 au.NM_ABNT_AUTOR,
 au.TP_AUTOR,
 NR_ORDEM,
 au.NM_AUTOR
INTO TCC.dbo.STEM
FROM TCC.dbo.artigos_periodicos ap
INNER JOIN TCC.dbo.prog_pos p ON p.CD_PROGRAMA_IES = ap.CD_PROGRAMA_IES AND ap.AN_BASE = p.AN_BASE
INNER JOIN TCC.dbo.autor_artigos_periodicos au ON au.ID_ADD_PRODUCAO_INTELECTUAL = ap.ID_ADD_PRODUCAO_INTELECTUAL AND au.AN_BASE = ap.AN_BASE 
INNER JOIN TCC.dbo.financiadores f ON f.CD_PROGRAMA_IES = ap.CD_PROGRAMA_IES AND f.ID_PROJETO = ap.ID_PROJETO AND ap.AN_BASE = f.AN_BASE
WHERE NM_GRANDE_AREA_CONHECIMENTO IN ('CIÊNCIAS EXATAS E DA TERRA', 'ENGENHARIAS')
ORDER BY p.AN_BASE